data=read.delim('clipboard')
data
str(data)
attach(data)
summary(data)

#Membuat histogram dan boxplot PDRB perkapita
hist(PDRB.Perkapita)
boxplot(PDRB.Perkapita)

#Mengestimasi parameter model dengan Metode Kuadrat Terkecil
library(foreign)
library(MASS)
library(olsrr)
MKT=lm(PDRB.Perkapita~.,data=data)
summary(MKT)
print(MKT)
plot(MKT$residuals)
ols_plot_dffits(MKT)

#Uji asumsi klasik
ks.test(MKT$residuals,"pnorm")
library(olsrr)
ols_vif_tol(MKT)
library(skedastic)
glejser(MKT)
library(lmtest)
dwtest(MKT)

#Mengidentifikasi pencilan
opar=par(mfrow=c(2,2),oma=c(0,0,1.1,0))
plot(MKT,las=1)
dffits=as.data.frame(dffits(MKT))
View(dffits)
k=length(MKT$coefficients)-1
n=nrow(data)
thresh=2*sqrt((k+1)/n)
thresh
data[which(abs(dffits(MKT))>thresh),]
plot(dffits(MKT),type = 'h')
abline(h=thresh,lty=2)
abline(h=-thresh,lty=2)
rstudent(MKT)

ols_plot_dffits(MKT)

#Mengestimasi parameter model dengan metode regresi robust
#Fungsi pembobot Huber
library(MASS)
hub<-rlm(PDRB.Perkapita~.,data=data,psi=psi.huber)
summary(hub)
print(hub)
hub1<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=1)
hub2<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=2)
hub3<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=3)
hub4<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=4)
hub5<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=5)
hub6<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=6)
hub7<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=7)
hub8<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=8)
hub9<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=9)
hub10<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=10)
hub11<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=11)
hub12<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=12)
hub13<-rlm(PDRB.Perkapita~.,data,psi=psi.huber,maxit=13)
print(hub1)
print(hub2)
print(hub3)
print(hub4)
print(hub5)
print(hub6)
print(hub7)
print(hub8)
print(hub9)
print(hub10)
print(hub11)
print(hub12)
print(hub13)
summary(hub13)

#Fungsi pembobot Tukey bisquare
bis<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare)
summary(bis)
print(bis)
bis1<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=1)
bis2<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=2)
bis3<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=3)
bis4<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=4)
bis5<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=5)
bis6<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=6)
bis7<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=7)
bis8<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=8)
bis9<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=9)
bis10<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=10)
bis11<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=11)
bis12<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=12)
bis13<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=13)
bis14<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=14)
bis15<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=15)
bis16<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=16)
bis17<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=17)
bis18<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=18)
bis19<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=19)
bis20<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=20)
bis21<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=21)
bis22<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=22)
bis23<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=23)
bis24<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=24)
bis25<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=25)
bis26<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=26)
bis27<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=27)
bis28<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=28)
bis29<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=29)
bis30<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=30)
bis31<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=31)
bis32<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=32)
bis33<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=33)
bis34<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=34)
bis35<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=35)
bis36<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=36)
bis37<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=37)
bis38<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=38)
bis39<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=39)
bis40<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=40)
bis41<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=41)
bis42<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=42)
bis43<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=43)
bis44<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=44)
bis45<-rlm(PDRB.Perkapita~.,data,psi=psi.bisquare,maxit=44)
print(bis1)
print(bis2)
print(bis3)
print(bis4)
print(bis5)
print(bis6)
print(bis7)
print(bis8)
print(bis9)
print(bis10)
print(bis11)
print(bis12)
print(bis13)
print(bis14)
print(bis15)
print(bis16)
print(bis17)
print(bis18)
print(bis19)
print(bis20)
print(bis21)
print(bis22)
print(bis23)
print(bis24)
print(bis25)
print(bis26)
print(bis27)
print(bis28)
print(bis29)
print(bis30)
print(bis31)
print(bis32)
print(bis33)
print(bis34)
print(bis35)
print(bis36)
print(bis37)
print(bis38)
print(bis39)
print(bis40)
print(bis41)
print(bis42)
print(bis43)
summary(43)
print(bis44)
print(bis45)
summary(bis43)
#Menghitung nilai adjusted R-Square dan nilai MSE 
#Fungsi pembobot Huber

SSE=sum((hub$residuals)^2)
SSE
SST=sum((data$PDRB.Perkapita-mean(data$PDRB.Perkapita))^2)
SST
MSE=SSE/n-(k+1)
MSE
x=SSE/n-(k+1)
y=SST/(n-1)
Rsq_adj=1-(x/y)
Rsq_adj
a=100-62.64
a
#Fungsi Pembobot Tukey bisquare
SSE1=sum((bis$residuals)^2)
SSE1
SST1=sum((data$PDRB.Perkapita-mean(data$PDRB.Perkapita))^2)
SST1
MSE1=SSE1/n-(k+1)
MSE1
x=SSE1/n-(k+1)
y=SST1/(n-1)
Rsq_adj=1-(x/y)
Rsq_adj


#metode estimasi-s
library (robustbase)
fittukey=lmrob(PDRB.Perkapita~., data= data,method="S", psi="tukey")
summary(fittukey)
pred2=predict(fittukey)

residu1=resid(fittukey)
mse1=mean(residu1^2)
mse1

fitwelsh=lmrob(PDRB.Perkapita~., data= data,method="S", psi="welsh")
summary(fitwelsh)
summary(lmrob(PDRB.Perkapita~., data= data,method="S", psi="welsh"),
        maxit=28)
residu1=resid(fitwelsh)
mse1=mean(residu1^2)
mse1
